### ISSUE TITLE
Terminal access also seconding the question of lxc use instead of vm

### ISSUE THREAD

**Issue by dasb00ter** [whiskerz007/proxmox_hassos_install#23]
First thanks a bunch! for this. I was just wondering if I should have access to xterm. I thought it was mentioned on DR ZZ's video but I could not get access once your virtual machine started. I needed to set the ip address and I couldnt copy and paste to novnc or spice so I typed it out and got it wrong once or twice lol.

Before giving up I tried to install hass.io on docker nested in an ubuntu 18.04 container. I had several containers in docker running nicely. Portainer, home assistant, and watch tower all ran fine in docker that way but I could not install hass.io . The install method [Alternative: install on generic Linux server](https://www.home-assistant.io/hassio/installation/)  only created a hypervisor and not fully functional hass.io. Wondered if you knew why? or would consider making a container running a similiar setup as the overhead for lxc containers is better than a virtual machine. 

If you do get back to reading this than big thanks for the proxmox virtual machine

**Comment by whiskerz007** [comment]
There is no SSH server install on the Hass.io OS. There is a HA Addon which add SSH, but it is confined and does not have the access needed to change the Hass.io IP address. Manually typing the commands are necessary at the moment.

I've attempted to get a properly functioning Hass.io deployment in an LXC, but there are a lot of limitations due to the security implementations. Proxmox has a set of security parameters that are very restrictive (by design, which is a good thing). Docker has a different set of security parameters, most of which assumes is running unconfined on the host OS. By the time you remove all of the limitations on the LXC so that Docker works properly, you've eliminated the purpose of running a LXC.

If you are desiring to run Docker containers on Proxmox, the best solution would be to install Docker natively on Proxmox. You will find people talking about that not being a good idea. The reason for their concern is because Docker will require many packages to be installed. This is ill advised because Proxmox is purpose built to be a hypervisor. If you are desiring to use Docker against best practices, follow the guides for installing onto a Debian system.

**Comment by dasb00ter** [comment]
Thanks so much for taking the time to answer my questions. Gotcha in terms of the LXC. My reason for using the LXC was simply a resource one (hoping to use an older but decently spec'd system) but I defer to your judgement in terms of security. I really do like the versatility of a docker set up. I think I was just looking for someone who knows what there doing to say there is more to a LXC set up than setting up an Ubuntu LXC and following the directions for an alternative Hass docker install
