### ISSUE TITLE
Ip address with instructions

### ISSUE THREAD

**Issue by jaygrovr** [whiskerz007/proxmox_hassos_install#57]
First, thank you whiskerz for doing this.  ITs great!..

I dont have the option to view the network interface settings on my summary page.  Did that go away with your latest image with instructions?

**Comment by jaygrovr** [comment]
![proxmoxCapture](https://user-images.githubusercontent.com/7143066/79385707-e15d7900-7f1d-11ea-849b-c21beaccf251.PNG)

**Comment by nickrout** [comment]
Same qustion.

**Comment by whiskerz007** [comment]
I just check with a new install and it seems to work for me. Please verify that you are still having this problem.

**Comment by mmatloka** [comment]
Just tried with 6.2-4  
![image](https://user-images.githubusercontent.com/82916/84565725-68d33700-ad6b-11ea-9993-b076d4959167.png)

**Comment by whiskerz007** [comment]
Running the script again and everything seems to work appropriately. After starting the VM, it will take a moment for the IP address to display. This is normal, because it will take some time for the application in the VM to start to report the IP address.
![image](https://user-images.githubusercontent.com/2713522/97436471-57598880-1922-11eb-80b5-1034302babc9.png)

Feel free to open the issue again if you still need assistance.
